version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
  - cmd: nuget restore
  - cmd: choco install codecov
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore 
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish -c Release
after_build:
  # For once the build has completed
artifacts:
  - path: './web/bin/Release/netcoreapp2.1/publish'
    name: WebSite
    type: WebDeployPackage
clone_depth: 1
test_script:
  # run the unit tests (requires changing into the test directory)
  - cmd: dotnet test -c Release --no-build test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - cmd: codecov -f "./test/coverage.xml" -t "a6d3bca4-2f90-4fc3-aa2c-04dd9abf1105"
on_finish :
  # any cleanup in here
  - bash <(curl -s https://codecov.io/bash)
deploy: off